name: Deno Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: For test

    env:
      QY_WECHAT_CORPID: ${{ secrets.QY_WECHAT_CORPID }}
      QY_WECHAT_QRLOGIN_AGENTID: ${{ secrets.QY_WECHAT_QRLOGIN_AGENTID }}
      QY_WECHAT_QRLOGIN_SECRET: ${{ secrets.QY_WECHAT_QRLOGIN_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: echo env
        run: echo ${{ secrets.TEST_SECRET }}

      - name: Run tests
        run: deno task test
